export const cozyTheme = {
  colors: {
    background: "#F7F1E7",
    surface: "#FFF9EF",
    surfaceMuted: "#F0E7DA",
    surfaceSoft: "#FBF4E8",
    border: "#E7DCCB",
    borderStrong: "#D8C9B5",
    text: "#2F2A24",
    textMuted: "#6F665B",
    textSubtle: "#9A8F80",
    primary: "#C9651E",
    primarySoft: "#F4D8C4",
    primarySurface: "#FBE8DA",
    kr: "#6D8551",
    krSoft: "#E7EEDC",
    global: "#587A9D",
    globalSoft: "#E2ECF5",
    positive: "#587A3F",
    positiveSoft: "#E7EEDC",
    negative: "#A95454",
    negativeSoft: "#F3DEDC",
    white: "#FFFFFF",
  },
  radius: {
    sm: 8,
    md: 10,
    lg: 12,
  },
  shadow: {
    color: "#2F2A24",
    opacity: 0.07,
  },
} as const;
